import Link from "next/link";
import { Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import { BrandLogo } from "@/components/shared/brand-logo";
import { InstallAppButton } from "@/components/pwa/install-app-button";
export function Footer() { return <footer className="border-t-4 border-warning bg-primary text-white"><div className="page-shell grid gap-10 py-14 md:grid-cols-2 lg:grid-cols-4">
  <div><BrandLogo className="max-w-[220px]"/><p className="mt-4 max-w-sm text-sm font-light leading-6 text-white/70">A plataforma que aproxima quem procura transporte de quem tem um truck disponível.</p><p className="mt-4 text-xs font-semibold uppercase tracking-[.16em] text-warning">Conectamos cargas. Movemos negócios.</p></div>
  <div><h3 className="font-heading font-semibold text-white">Navegação</h3><ul className="mt-4 space-y-3 text-sm text-white/65"><li><Link href="/trucks" className="hover:text-warning">Transport</Link></li><li><Link href="/location" className="hover:text-warning">Location</Link></li><li><Link href="/vente" className="hover:text-warning">Vente</Link></li><li><Link href="/entreprises" className="hover:text-warning">Entreprises</Link></li><li><Link href="/comment-ca-marche" className="hover:text-warning">Comment ça marche</Link></li></ul></div>
  <div><h3 className="font-heading font-semibold text-white">Contactos</h3><ul className="mt-4 space-y-3 text-sm text-white/65"><li className="flex gap-2"><Phone className="size-4 text-warning"/>+245 955 000 100</li><li className="flex gap-2"><MessageCircle className="size-4 text-warning"/>WhatsApp AgroTruck</li><li className="flex gap-2"><Mail className="size-4 text-warning"/>contact@agrotruck.gw</li><li className="flex gap-2"><MapPin className="size-4 text-warning"/>Bissau, Guiné-Bissau</li></ul></div>
  <div><h3 className="font-heading font-semibold text-white">Aplicação</h3><p className="mt-4 mb-4 text-sm font-light leading-6 text-white/65">Instale AgroTruck no seu telefone para aceder mais rapidamente.</p><InstallAppButton/><ul className="mt-5 space-y-3 text-sm text-white/65"><li><Link href="#" className="hover:text-warning">Política de privacidade</Link></li><li><Link href="#" className="hover:text-warning">Termos de utilização</Link></li></ul></div>
</div><div className="border-t border-white/10 py-5 text-center text-xs text-white/50">© {new Date().getFullYear()} AgroTruck. Todos os direitos reservados.</div></footer>; }
