"use client";

import { cloneElement, isValidElement, useId, useMemo, useState, type ReactElement } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { ArrowLeft, ArrowRight, CheckCircle2, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { materials, locations } from "@/data/trucks";
import { truckTypeLabels } from "@/types/truck";

const baseSchema = z.object({
  name:z.string().min(2,"Indique o seu nome."), phone:z.string().min(7,"Número de telefone inválido."), whatsapp:z.string().min(7,"Número de WhatsApp inválido."), email:z.email("Email inválido."), city:z.string().min(1,"Escolha a sua cidade."), companyName:z.string().optional(),
  truckType:z.string().min(1,"Escolha um tipo de truck."), brand:z.string().min(2,"Indique a marca."), model:z.string().min(1,"Indique o modelo."), capacity:z.number({message:"Indique a capacidade."}).min(1,"A capacidade deve ser superior a 0."), registration:z.string().min(3,"Indique a matrícula."), acceptedMaterials:z.array(z.string()).min(1,"Escolha pelo menos uma mercadoria."), serviceAreas:z.array(z.string()).min(1,"Escolha pelo menos uma zona."),
  driverName:z.string().optional(), driverPhone:z.string().optional(), apprenticeName:z.string().optional(), apprenticePhone:z.string().optional(), terms:z.boolean().refine(Boolean,"Deve aceitar os termos."),
});

function formSchema(accountType:"individual"|"company") { return baseSchema.superRefine((data,ctx)=>{if(accountType!=="company")return;if(!data.companyName?.trim())ctx.addIssue({code:"custom",path:["companyName"],message:"Indique o nome da empresa."});for(const [field,message] of [["driverName","Indique o nome do motorista."],["driverPhone","Indique o telefone do motorista."],["apprenticeName","Indique o nome do ajudante."],["apprenticePhone","Indique o telefone do ajudante."]] as const){if(!data[field]?.trim())ctx.addIssue({code:"custom",path:[field],message})}}); }
export type PartnerFormData=z.infer<typeof baseSchema>;
const stepFields:(keyof PartnerFormData)[][]=[["name","phone","whatsapp","email","city","companyName"],["truckType","brand","model","capacity","registration","acceptedMaterials","serviceAreas","driverName","driverPhone","apprenticeName","apprenticePhone"],["terms"]];

export function PartnerForm({verifiedEmail,accountType,onCompleted}:{verifiedEmail:string;accountType:"individual"|"company";onCompleted:(data:PartnerFormData)=>void}){
  const [step,setStep]=useState(0); const schema=useMemo(()=>formSchema(accountType),[accountType]);
  const {register,handleSubmit,trigger,formState:{errors}}=useForm<PartnerFormData>({resolver:zodResolver(schema),defaultValues:{email:verifiedEmail,acceptedMaterials:[],serviceAreas:[],terms:false}});
  async function next(){if(await trigger(stepFields[step]))setStep(value=>Math.min(2,value+1));}
  return <form onSubmit={handleSubmit(onCompleted)} noValidate>
    <div className="mb-7 flex items-center justify-between rounded-2xl border border-primary/10 bg-white px-4 py-3"><div><p className="text-[10px] font-bold uppercase tracking-[.15em] text-muted-foreground">Perfil guardado</p><p className="mt-1 font-heading font-bold text-primary">{accountType==="company"?"Empresa · 1 000 000 FCFA":"Particular · 50 000 FCFA por truck"}</p></div><CheckCircle2 className="size-5 text-emerald-600"/></div>
    <div className="mb-8 grid grid-cols-3 gap-2">{["Contacto","Truck","Confirmação"].map((label,index)=><div key={label}><div className={`h-1.5 rounded-full ${index<=step?"bg-primary":"bg-primary/10"}`}/><p className={`mt-2 hidden text-xs sm:block ${index===step?"font-bold text-primary":"text-[#766f63]"}`}>{index+1}. {label}</p></div>)}</div>
    <div className="glass-panel rounded-3xl bg-white/85 p-5 md:p-8">
      {step===0&&<Step title="Os seus contactos" text="Os clientes usarão estes dados para falar diretamente consigo."><div className="grid gap-5 md:grid-cols-2"><Field label="Nome completo" error={errors.name?.message}><Input {...register("name")}/></Field><Field label="Telefone" error={errors.phone?.message}><Input type="tel" placeholder="+245 ..." {...register("phone")}/></Field><Field label="WhatsApp" error={errors.whatsapp?.message}><Input type="tel" placeholder="+245 ..." {...register("whatsapp")}/></Field><Field label="Email da conta" error={errors.email?.message}><Input type="email" readOnly className="bg-primary/5" {...register("email")}/></Field><Field label="Cidade" error={errors.city?.message}><Select {...register("city")}><option value="">Escolher uma cidade</option>{locations.map(location=><option key={location}>{location}</option>)}</Select></Field>{accountType==="company"&&<Field label="Nome da empresa" error={errors.companyName?.message}><Input {...register("companyName")}/></Field>}</div></Step>}
      {step===1&&<Step title="Apresente o seu truck" text="Informações precisas ajudam os clientes a decidir."><div className="grid gap-5 md:grid-cols-2"><Field label="Tipo de truck" error={errors.truckType?.message}><Select {...register("truckType")}><option value="">Escolher</option>{Object.entries(truckTypeLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</Select></Field><Field label="Marca" error={errors.brand?.message}><Input {...register("brand")}/></Field><Field label="Modelo" error={errors.model?.message}><Input {...register("model")}/></Field><Field label="Capacidade (toneladas)" error={errors.capacity?.message}><Input type="number" {...register("capacity",{valueAsNumber:true})}/></Field><Field label="Matrícula" error={errors.registration?.message}><Input {...register("registration")}/></Field></div><CheckGroup label="Mercadorias aceites" items={materials} field="acceptedMaterials" register={register} error={errors.acceptedMaterials?.message}/><CheckGroup label="Zonas de serviço" items={locations} field="serviceAreas" register={register} error={errors.serviceAreas?.message}/>{accountType==="company"&&<div className="mt-8 rounded-2xl border border-primary/10 bg-primary/[.035] p-5"><div className="mb-5 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-primary text-white"><UsersRound className="size-5"/></span><div><h3 className="font-heading font-bold text-primary">Equipa atribuída</h3><p className="text-xs text-muted-foreground">Poderá alterar esta equipa no dashboard.</p></div></div><div className="grid gap-5 md:grid-cols-2"><Field label="Nome do motorista" error={errors.driverName?.message}><Input {...register("driverName")}/></Field><Field label="Telefone do motorista" error={errors.driverPhone?.message}><Input type="tel" {...register("driverPhone")}/></Field><Field label="Nome do ajudante" error={errors.apprenticeName?.message}><Input {...register("apprenticeName")}/></Field><Field label="Telefone do ajudante" error={errors.apprenticePhone?.message}><Input type="tel" {...register("apprenticePhone")}/></Field></div></div>}</Step>}
      {step===2&&<Step title="Confirmação" text="Confirme os dados antes de enviar o truck para validação."><div className="rounded-2xl border border-warning/25 bg-warning/10 p-5 text-sm leading-6 text-foreground/75"><strong className="block text-foreground">O truck ficará em espera.</strong>Depois do pagamento em dinheiro, o administrador valida o truck. Só então poderá colocá-lo online no dashboard.</div><label className="mt-6 flex items-start gap-3 rounded-xl border border-primary/10 p-4 text-sm text-[#4e4a43]"><input type="checkbox" className="mt-1 accent-[#0B3D2E]" {...register("terms")}/><span>Confirmo que os dados estão corretos e aceito os termos de utilização.</span></label><Error message={errors.terms?.message}/></Step>}
      <div className="mt-8 flex justify-between gap-3">{step>0?<Button type="button" variant="secondary" onClick={()=>setStep(value=>value-1)}><ArrowLeft className="size-4"/>Voltar</Button>:<span/>}{step<2?<Button type="button" onClick={next}>Continuar <ArrowRight className="size-4"/></Button>:<Button type="submit">Cadastrar truck <CheckCircle2 className="size-4"/></Button>}</div>
    </div>
  </form>;
}

function Step({title,text,children}:{title:string;text:string;children:React.ReactNode}){return <div><h2 className="font-heading text-2xl font-extrabold text-primary md:text-3xl">{title}</h2><p className="mb-7 mt-2 text-sm text-[#6e685e]">{text}</p>{children}</div>}
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){const id=useId();const control=isValidElement(children)?cloneElement(children as ReactElement<{id?:string;"aria-invalid"?:boolean}>,{id,"aria-invalid":Boolean(error)}):children;return <div><Label htmlFor={id}>{label}</Label>{control}<Error message={error}/></div>}
function Error({message}:{message?:string}){return message?<p role="alert" className="mt-2 text-xs font-medium text-danger">{message}</p>:null}
function CheckGroup({label,items,field,register,error}:{label:string;items:string[];field:"acceptedMaterials"|"serviceAreas";register:ReturnType<typeof useForm<PartnerFormData>>["register"];error?:string}){return <fieldset className="mt-7"><legend className="mb-3 text-sm font-bold text-primary">{label}</legend><div className="flex flex-wrap gap-2">{items.map(item=><label key={item} className="cursor-pointer rounded-lg border border-primary/15 bg-white px-3 py-2 text-xs text-[#4e4a43] has-[:checked]:border-primary has-[:checked]:bg-primary/10 has-[:checked]:text-primary"><input type="checkbox" value={item} className="sr-only" {...register(field)}/>{item}</label>)}</div><Error message={error}/></fieldset>}
