/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangAboutRouteImport } from './routes/$lang/about'
import { Route as LangFleetRouteImport } from './routes/$lang/fleet'
import { Route as LangHowItWorksRouteImport } from './routes/$lang/how-it-works'
import { Route as LangLoginRouteImport } from './routes/$lang/login'
import { Route as LangOfflineRouteImport } from './routes/$lang/offline'
import { Route as LangPricingRouteImport } from './routes/$lang/pricing'
import { Route as LangProfileRouteImport } from './routes/$lang/profile'
import { Route as LangRentalRouteImport } from './routes/$lang/rental'
import { Route as LangSaleRouteImport } from './routes/$lang/sale'
import { Route as LangSignupRouteImport } from './routes/$lang/signup'
import { Route as LangAdminIndexRouteImport } from './routes/$lang/admin/index'
import { Route as LangAdminMissionsRouteImport } from './routes/$lang/admin/missions'
import { Route as LangAdminTrucksRouteImport } from './routes/$lang/admin/trucks'
import { Route as LangAdminUsersRouteImport } from './routes/$lang/admin/users'
import { Route as LangProducerIndexRouteImport } from './routes/$lang/producer/index'
import { Route as LangProducerNewRouteImport } from './routes/$lang/producer/new'
import { Route as LangTrackTokenRouteImport } from './routes/$lang/track.$token'
import { Route as LangTransporterIndexRouteImport } from './routes/$lang/transporter/index'
import { Route as LangTransporterDriversRouteImport } from './routes/$lang/transporter/drivers'
import { Route as LangTransporterFleetRouteImport } from './routes/$lang/transporter/fleet'
import { Route as LangTrucksSlugRouteImport } from './routes/$lang/trucks.$slug'
import { Route as LangProducerMissionsMissionIdRouteImport } from './routes/$lang/producer/missions.$missionId'
import { Route as LangTransporterMissionsIndexRouteImport } from './routes/$lang/transporter/missions.index'
import { Route as LangTransporterMissionsMissionIdRouteImport } from './routes/$lang/transporter/missions.$missionId'
import { Route as LangTransporterTrucksIndexRouteImport } from './routes/$lang/transporter/trucks.index'
import { Route as LangTransporterTrucksTruckIdRouteImport } from './routes/$lang/transporter/trucks.$truckId'
import { Route as LangTransporterTrucksNewRouteImport } from './routes/$lang/transporter/trucks.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)
const LangFleetRoute = LangFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => LangRoute,
} as any)
const LangHowItWorksRoute = LangHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => LangRoute,
} as any)
const LangLoginRoute = LangLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LangRoute,
} as any)
const LangOfflineRoute = LangOfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => LangRoute,
} as any)
const LangPricingRoute = LangPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => LangRoute,
} as any)
const LangProfileRoute = LangProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LangRoute,
} as any)
const LangRentalRoute = LangRentalRouteImport.update({
  id: '/rental',
  path: '/rental',
  getParentRoute: () => LangRoute,
} as any)
const LangSaleRoute = LangSaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => LangRoute,
} as any)
const LangSignupRoute = LangSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminIndexRoute = LangAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminMissionsRoute = LangAdminMissionsRouteImport.update({
  id: '/admin/missions',
  path: '/admin/missions',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminTrucksRoute = LangAdminTrucksRouteImport.update({
  id: '/admin/trucks',
  path: '/admin/trucks',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminUsersRoute = LangAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => LangRoute,
} as any)
const LangProducerIndexRoute = LangProducerIndexRouteImport.update({
  id: '/producer/',
  path: '/producer/',
  getParentRoute: () => LangRoute,
} as any)
const LangProducerNewRoute = LangProducerNewRouteImport.update({
  id: '/producer/new',
  path: '/producer/new',
  getParentRoute: () => LangRoute,
} as any)
const LangTrackTokenRoute = LangTrackTokenRouteImport.update({
  id: '/track/$token',
  path: '/track/$token',
  getParentRoute: () => LangRoute,
} as any)
const LangTransporterIndexRoute = LangTransporterIndexRouteImport.update({
  id: '/transporter/',
  path: '/transporter/',
  getParentRoute: () => LangRoute,
} as any)
const LangTransporterDriversRoute = LangTransporterDriversRouteImport.update({
  id: '/transporter/drivers',
  path: '/transporter/drivers',
  getParentRoute: () => LangRoute,
} as any)
const LangTransporterFleetRoute = LangTransporterFleetRouteImport.update({
  id: '/transporter/fleet',
  path: '/transporter/fleet',
  getParentRoute: () => LangRoute,
} as any)
const LangTrucksSlugRoute = LangTrucksSlugRouteImport.update({
  id: '/trucks/$slug',
  path: '/trucks/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangProducerMissionsMissionIdRoute =
  LangProducerMissionsMissionIdRouteImport.update({
    id: '/producer/missions/$missionId',
    path: '/producer/missions/$missionId',
    getParentRoute: () => LangRoute,
  } as any)
const LangTransporterMissionsIndexRoute =
  LangTransporterMissionsIndexRouteImport.update({
    id: '/transporter/missions/',
    path: '/transporter/missions/',
    getParentRoute: () => LangRoute,
  } as any)
const LangTransporterMissionsMissionIdRoute =
  LangTransporterMissionsMissionIdRouteImport.update({
    id: '/transporter/missions/$missionId',
    path: '/transporter/missions/$missionId',
    getParentRoute: () => LangRoute,
  } as any)
const LangTransporterTrucksIndexRoute =
  LangTransporterTrucksIndexRouteImport.update({
    id: '/transporter/trucks/',
    path: '/transporter/trucks/',
    getParentRoute: () => LangRoute,
  } as any)
const LangTransporterTrucksTruckIdRoute =
  LangTransporterTrucksTruckIdRouteImport.update({
    id: '/transporter/trucks/$truckId',
    path: '/transporter/trucks/$truckId',
    getParentRoute: () => LangRoute,
  } as any)
const LangTransporterTrucksNewRoute =
  LangTransporterTrucksNewRouteImport.update({
    id: '/transporter/trucks/new',
    path: '/transporter/trucks/new',
    getParentRoute: () => LangRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/fleet': typeof LangFleetRoute
  '/$lang/how-it-works': typeof LangHowItWorksRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/offline': typeof LangOfflineRoute
  '/$lang/pricing': typeof LangPricingRoute
  '/$lang/profile': typeof LangProfileRoute
  '/$lang/rental': typeof LangRentalRoute
  '/$lang/sale': typeof LangSaleRoute
  '/$lang/signup': typeof LangSignupRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/admin/missions': typeof LangAdminMissionsRoute
  '/$lang/admin/trucks': typeof LangAdminTrucksRoute
  '/$lang/admin/users': typeof LangAdminUsersRoute
  '/$lang/producer/new': typeof LangProducerNewRoute
  '/$lang/track/$token': typeof LangTrackTokenRoute
  '/$lang/transporter/drivers': typeof LangTransporterDriversRoute
  '/$lang/transporter/fleet': typeof LangTransporterFleetRoute
  '/$lang/trucks/$slug': typeof LangTrucksSlugRoute
  '/$lang/admin/': typeof LangAdminIndexRoute
  '/$lang/producer/': typeof LangProducerIndexRoute
  '/$lang/transporter/': typeof LangTransporterIndexRoute
  '/$lang/producer/missions/$missionId': typeof LangProducerMissionsMissionIdRoute
  '/$lang/transporter/missions/$missionId': typeof LangTransporterMissionsMissionIdRoute
  '/$lang/transporter/trucks/$truckId': typeof LangTransporterTrucksTruckIdRoute
  '/$lang/transporter/trucks/new': typeof LangTransporterTrucksNewRoute
  '/$lang/transporter/missions/': typeof LangTransporterMissionsIndexRoute
  '/$lang/transporter/trucks/': typeof LangTransporterTrucksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/fleet': typeof LangFleetRoute
  '/$lang/how-it-works': typeof LangHowItWorksRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/offline': typeof LangOfflineRoute
  '/$lang/pricing': typeof LangPricingRoute
  '/$lang/profile': typeof LangProfileRoute
  '/$lang/rental': typeof LangRentalRoute
  '/$lang/sale': typeof LangSaleRoute
  '/$lang/signup': typeof LangSignupRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/admin/missions': typeof LangAdminMissionsRoute
  '/$lang/admin/trucks': typeof LangAdminTrucksRoute
  '/$lang/admin/users': typeof LangAdminUsersRoute
  '/$lang/producer/new': typeof LangProducerNewRoute
  '/$lang/track/$token': typeof LangTrackTokenRoute
  '/$lang/transporter/drivers': typeof LangTransporterDriversRoute
  '/$lang/transporter/fleet': typeof LangTransporterFleetRoute
  '/$lang/trucks/$slug': typeof LangTrucksSlugRoute
  '/$lang/admin': typeof LangAdminIndexRoute
  '/$lang/producer': typeof LangProducerIndexRoute
  '/$lang/transporter': typeof LangTransporterIndexRoute
  '/$lang/producer/missions/$missionId': typeof LangProducerMissionsMissionIdRoute
  '/$lang/transporter/missions/$missionId': typeof LangTransporterMissionsMissionIdRoute
  '/$lang/transporter/trucks/$truckId': typeof LangTransporterTrucksTruckIdRoute
  '/$lang/transporter/trucks/new': typeof LangTransporterTrucksNewRoute
  '/$lang/transporter/missions': typeof LangTransporterMissionsIndexRoute
  '/$lang/transporter/trucks': typeof LangTransporterTrucksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/fleet': typeof LangFleetRoute
  '/$lang/how-it-works': typeof LangHowItWorksRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/offline': typeof LangOfflineRoute
  '/$lang/pricing': typeof LangPricingRoute
  '/$lang/profile': typeof LangProfileRoute
  '/$lang/rental': typeof LangRentalRoute
  '/$lang/sale': typeof LangSaleRoute
  '/$lang/signup': typeof LangSignupRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/admin/missions': typeof LangAdminMissionsRoute
  '/$lang/admin/trucks': typeof LangAdminTrucksRoute
  '/$lang/admin/users': typeof LangAdminUsersRoute
  '/$lang/producer/new': typeof LangProducerNewRoute
  '/$lang/track/$token': typeof LangTrackTokenRoute
  '/$lang/transporter/drivers': typeof LangTransporterDriversRoute
  '/$lang/transporter/fleet': typeof LangTransporterFleetRoute
  '/$lang/trucks/$slug': typeof LangTrucksSlugRoute
  '/$lang/admin/': typeof LangAdminIndexRoute
  '/$lang/producer/': typeof LangProducerIndexRoute
  '/$lang/transporter/': typeof LangTransporterIndexRoute
  '/$lang/producer/missions/$missionId': typeof LangProducerMissionsMissionIdRoute
  '/$lang/transporter/missions/$missionId': typeof LangTransporterMissionsMissionIdRoute
  '/$lang/transporter/trucks/$truckId': typeof LangTransporterTrucksTruckIdRoute
  '/$lang/transporter/trucks/new': typeof LangTransporterTrucksNewRoute
  '/$lang/transporter/missions/': typeof LangTransporterMissionsIndexRoute
  '/$lang/transporter/trucks/': typeof LangTransporterTrucksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/fleet'
    | '/$lang/how-it-works'
    | '/$lang/login'
    | '/$lang/offline'
    | '/$lang/pricing'
    | '/$lang/profile'
    | '/$lang/rental'
    | '/$lang/sale'
    | '/$lang/signup'
    | '/$lang/'
    | '/$lang/admin/missions'
    | '/$lang/admin/trucks'
    | '/$lang/admin/users'
    | '/$lang/producer/new'
    | '/$lang/track/$token'
    | '/$lang/transporter/drivers'
    | '/$lang/transporter/fleet'
    | '/$lang/trucks/$slug'
    | '/$lang/admin/'
    | '/$lang/producer/'
    | '/$lang/transporter/'
    | '/$lang/producer/missions/$missionId'
    | '/$lang/transporter/missions/$missionId'
    | '/$lang/transporter/trucks/$truckId'
    | '/$lang/transporter/trucks/new'
    | '/$lang/transporter/missions/'
    | '/$lang/transporter/trucks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/fleet'
    | '/$lang/how-it-works'
    | '/$lang/login'
    | '/$lang/offline'
    | '/$lang/pricing'
    | '/$lang/profile'
    | '/$lang/rental'
    | '/$lang/sale'
    | '/$lang/signup'
    | '/$lang'
    | '/$lang/admin/missions'
    | '/$lang/admin/trucks'
    | '/$lang/admin/users'
    | '/$lang/producer/new'
    | '/$lang/track/$token'
    | '/$lang/transporter/drivers'
    | '/$lang/transporter/fleet'
    | '/$lang/trucks/$slug'
    | '/$lang/admin'
    | '/$lang/producer'
    | '/$lang/transporter'
    | '/$lang/producer/missions/$missionId'
    | '/$lang/transporter/missions/$missionId'
    | '/$lang/transporter/trucks/$truckId'
    | '/$lang/transporter/trucks/new'
    | '/$lang/transporter/missions'
    | '/$lang/transporter/trucks'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/fleet'
    | '/$lang/how-it-works'
    | '/$lang/login'
    | '/$lang/offline'
    | '/$lang/pricing'
    | '/$lang/profile'
    | '/$lang/rental'
    | '/$lang/sale'
    | '/$lang/signup'
    | '/$lang/'
    | '/$lang/admin/missions'
    | '/$lang/admin/trucks'
    | '/$lang/admin/users'
    | '/$lang/producer/new'
    | '/$lang/track/$token'
    | '/$lang/transporter/drivers'
    | '/$lang/transporter/fleet'
    | '/$lang/trucks/$slug'
    | '/$lang/admin/'
    | '/$lang/producer/'
    | '/$lang/transporter/'
    | '/$lang/producer/missions/$missionId'
    | '/$lang/transporter/missions/$missionId'
    | '/$lang/transporter/trucks/$truckId'
    | '/$lang/transporter/trucks/new'
    | '/$lang/transporter/missions/'
    | '/$lang/transporter/trucks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/fleet': {
      id: '/$lang/fleet'
      path: '/fleet'
      fullPath: '/$lang/fleet'
      preLoaderRoute: typeof LangFleetRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/how-it-works': {
      id: '/$lang/how-it-works'
      path: '/how-it-works'
      fullPath: '/$lang/how-it-works'
      preLoaderRoute: typeof LangHowItWorksRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/login': {
      id: '/$lang/login'
      path: '/login'
      fullPath: '/$lang/login'
      preLoaderRoute: typeof LangLoginRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/offline': {
      id: '/$lang/offline'
      path: '/offline'
      fullPath: '/$lang/offline'
      preLoaderRoute: typeof LangOfflineRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/pricing': {
      id: '/$lang/pricing'
      path: '/pricing'
      fullPath: '/$lang/pricing'
      preLoaderRoute: typeof LangPricingRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/profile': {
      id: '/$lang/profile'
      path: '/profile'
      fullPath: '/$lang/profile'
      preLoaderRoute: typeof LangProfileRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/rental': {
      id: '/$lang/rental'
      path: '/rental'
      fullPath: '/$lang/rental'
      preLoaderRoute: typeof LangRentalRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/sale': {
      id: '/$lang/sale'
      path: '/sale'
      fullPath: '/$lang/sale'
      preLoaderRoute: typeof LangSaleRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/signup': {
      id: '/$lang/signup'
      path: '/signup'
      fullPath: '/$lang/signup'
      preLoaderRoute: typeof LangSignupRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin/': {
      id: '/$lang/admin/'
      path: '/admin'
      fullPath: '/$lang/admin/'
      preLoaderRoute: typeof LangAdminIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin/missions': {
      id: '/$lang/admin/missions'
      path: '/admin/missions'
      fullPath: '/$lang/admin/missions'
      preLoaderRoute: typeof LangAdminMissionsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin/trucks': {
      id: '/$lang/admin/trucks'
      path: '/admin/trucks'
      fullPath: '/$lang/admin/trucks'
      preLoaderRoute: typeof LangAdminTrucksRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin/users': {
      id: '/$lang/admin/users'
      path: '/admin/users'
      fullPath: '/$lang/admin/users'
      preLoaderRoute: typeof LangAdminUsersRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/producer/': {
      id: '/$lang/producer/'
      path: '/producer'
      fullPath: '/$lang/producer/'
      preLoaderRoute: typeof LangProducerIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/producer/new': {
      id: '/$lang/producer/new'
      path: '/producer/new'
      fullPath: '/$lang/producer/new'
      preLoaderRoute: typeof LangProducerNewRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/track/$token': {
      id: '/$lang/track/$token'
      path: '/track/$token'
      fullPath: '/$lang/track/$token'
      preLoaderRoute: typeof LangTrackTokenRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/transporter/': {
      id: '/$lang/transporter/'
      path: '/transporter'
      fullPath: '/$lang/transporter/'
      preLoaderRoute: typeof LangTransporterIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/transporter/drivers': {
      id: '/$lang/transporter/drivers'
      path: '/transporter/drivers'
      fullPath: '/$lang/transporter/drivers'
      preLoaderRoute: typeof LangTransporterDriversRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/transporter/fleet': {
      id: '/$lang/transporter/fleet'
      path: '/transporter/fleet'
      fullPath: '/$lang/transporter/fleet'
      preLoaderRoute: typeof LangTransporterFleetRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/trucks/$slug': {
      id: '/$lang/trucks/$slug'
      path: '/trucks/$slug'
      fullPath: '/$lang/trucks/$slug'
      preLoaderRoute: typeof LangTrucksSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/producer/missions/$missionId': {
      id: '/$lang/producer/missions/$missionId'
      path: '/producer/missions/$missionId'
      fullPath: '/$lang/producer/missions/$missionId'
      preLoaderRoute: typeof LangProducerMissionsMissionIdRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/transporter/missions/': {
      id: '/$lang/transporter/missions/'
      path: '/transporter/missions'
      fullPath: '/$lang/transporter/missions/'
      preLoaderRoute: typeof LangTransporterMissionsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/transporter/missions/$missionId': {
      id: '/$lang/transporter/missions/$missionId'
      path: '/transporter/missions/$missionId'
      fullPath: '/$lang/transporter/missions/$missionId'
      preLoaderRoute: typeof LangTransporterMissionsMissionIdRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/transporter/trucks/': {
      id: '/$lang/transporter/trucks/'
      path: '/transporter/trucks'
      fullPath: '/$lang/transporter/trucks/'
      preLoaderRoute: typeof LangTransporterTrucksIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/transporter/trucks/$truckId': {
      id: '/$lang/transporter/trucks/$truckId'
      path: '/transporter/trucks/$truckId'
      fullPath: '/$lang/transporter/trucks/$truckId'
      preLoaderRoute: typeof LangTransporterTrucksTruckIdRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/transporter/trucks/new': {
      id: '/$lang/transporter/trucks/new'
      path: '/transporter/trucks/new'
      fullPath: '/$lang/transporter/trucks/new'
      preLoaderRoute: typeof LangTransporterTrucksNewRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangFleetRoute: typeof LangFleetRoute
  LangHowItWorksRoute: typeof LangHowItWorksRoute
  LangLoginRoute: typeof LangLoginRoute
  LangOfflineRoute: typeof LangOfflineRoute
  LangPricingRoute: typeof LangPricingRoute
  LangProfileRoute: typeof LangProfileRoute
  LangRentalRoute: typeof LangRentalRoute
  LangSaleRoute: typeof LangSaleRoute
  LangSignupRoute: typeof LangSignupRoute
  LangIndexRoute: typeof LangIndexRoute
  LangAdminMissionsRoute: typeof LangAdminMissionsRoute
  LangAdminTrucksRoute: typeof LangAdminTrucksRoute
  LangAdminUsersRoute: typeof LangAdminUsersRoute
  LangProducerNewRoute: typeof LangProducerNewRoute
  LangTrackTokenRoute: typeof LangTrackTokenRoute
  LangTransporterDriversRoute: typeof LangTransporterDriversRoute
  LangTransporterFleetRoute: typeof LangTransporterFleetRoute
  LangTrucksSlugRoute: typeof LangTrucksSlugRoute
  LangAdminIndexRoute: typeof LangAdminIndexRoute
  LangProducerIndexRoute: typeof LangProducerIndexRoute
  LangTransporterIndexRoute: typeof LangTransporterIndexRoute
  LangProducerMissionsMissionIdRoute: typeof LangProducerMissionsMissionIdRoute
  LangTransporterMissionsMissionIdRoute: typeof LangTransporterMissionsMissionIdRoute
  LangTransporterTrucksTruckIdRoute: typeof LangTransporterTrucksTruckIdRoute
  LangTransporterTrucksNewRoute: typeof LangTransporterTrucksNewRoute
  LangTransporterMissionsIndexRoute: typeof LangTransporterMissionsIndexRoute
  LangTransporterTrucksIndexRoute: typeof LangTransporterTrucksIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangFleetRoute: LangFleetRoute,
  LangHowItWorksRoute: LangHowItWorksRoute,
  LangLoginRoute: LangLoginRoute,
  LangOfflineRoute: LangOfflineRoute,
  LangPricingRoute: LangPricingRoute,
  LangProfileRoute: LangProfileRoute,
  LangRentalRoute: LangRentalRoute,
  LangSaleRoute: LangSaleRoute,
  LangSignupRoute: LangSignupRoute,
  LangIndexRoute: LangIndexRoute,
  LangAdminMissionsRoute: LangAdminMissionsRoute,
  LangAdminTrucksRoute: LangAdminTrucksRoute,
  LangAdminUsersRoute: LangAdminUsersRoute,
  LangProducerNewRoute: LangProducerNewRoute,
  LangTrackTokenRoute: LangTrackTokenRoute,
  LangTransporterDriversRoute: LangTransporterDriversRoute,
  LangTransporterFleetRoute: LangTransporterFleetRoute,
  LangTrucksSlugRoute: LangTrucksSlugRoute,
  LangAdminIndexRoute: LangAdminIndexRoute,
  LangProducerIndexRoute: LangProducerIndexRoute,
  LangTransporterIndexRoute: LangTransporterIndexRoute,
  LangProducerMissionsMissionIdRoute: LangProducerMissionsMissionIdRoute,
  LangTransporterMissionsMissionIdRoute: LangTransporterMissionsMissionIdRoute,
  LangTransporterTrucksTruckIdRoute: LangTransporterTrucksTruckIdRoute,
  LangTransporterTrucksNewRoute: LangTransporterTrucksNewRoute,
  LangTransporterMissionsIndexRoute: LangTransporterMissionsIndexRoute,
  LangTransporterTrucksIndexRoute: LangTransporterTrucksIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
