import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Building2, Check, Clock3, ShieldCheck, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = { title: "Preços", description: "Planos de publicação AgroTruck para particulares e empresas de transporte." };

const shared = ["Pagamento único, sem mensalidade", "Contacto direto por telefone e WhatsApp", "Validação da AgroTruck antes da primeira publicação", "Controlo da disponibilidade pelo proprietário"];

export default function PricingPage() {
  return <main className="min-h-[70vh] bg-[#f8f8f5] pb-24">
    <section className="relative overflow-hidden bg-primary py-16 text-white md:py-24"><div className="absolute inset-x-0 top-0 brand-road rounded-none"/><div className="page-shell text-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-warning">Pagamento único</p><h1 className="mx-auto mt-4 max-w-4xl font-heading text-4xl font-extrabold tracking-[-.045em] text-white md:text-6xl">Publique a sua frota uma vez. Fique visível sem mensalidade.</h1><p className="mx-auto mt-5 max-w-2xl font-light leading-7 text-white/70">Escolha o perfil adequado ao número de trucks. A publicação acontece depois da confirmação manual do pagamento.</p></div></section>
    <section className="page-shell -mt-8 relative z-10 grid gap-5 md:grid-cols-2 md:gap-6">
      <Plan icon={<UserRound/>} name="Particular" description="Para proprietários com uma pequena frota." price="50 000" suffix="FCFA / truck" limit="Máximo de 5 trucks" items={shared}/>
      <Plan featured icon={<Building2/>} name="Empresa" description="Para transportadoras e frotas profissionais." price="1 000 000" suffix="FCFA" limit="5 trucks ou mais" items={[...shared, "Página dedicada para a empresa", "Toda a frota agrupada num único perfil"]}/>
    </section>
    <section className="page-shell mt-12"><div className="grid gap-6 rounded-[20px] border border-warning/35 bg-warning/[.09] p-6 md:grid-cols-[auto_1fr_auto] md:items-center md:p-8"><span className="grid size-12 place-items-center rounded-full bg-warning text-[#111]"><Clock3 className="size-5"/></span><div><h2 className="font-heading text-xl font-bold">Como funciona a validação?</h2><p className="mt-1 text-sm font-light leading-6 text-muted-foreground">Cadastre o truck, efetue o pagamento indicado pela AgroTruck e aguarde a confirmação do administrador. Depois, coloque-o online quando estiver pronto para receber contactos.</p></div><Button asChild><Link href="/devenir-partenaire">Cadastrar truck <ArrowRight className="size-4"/></Link></Button></div></section>
  </main>;
}

function Plan({ icon, name, description, price, suffix, limit, items, featured = false }: { icon: React.ReactNode; name: string; description: string; price: string; suffix: string; limit: string; items: string[]; featured?: boolean }) {
  return <article className={`relative overflow-hidden rounded-[24px] border p-6 shadow-[0_20px_55px_rgba(11,61,46,.08)] md:p-8 ${featured ? "border-primary bg-primary text-white" : "border-primary/10 bg-white"}`}>{featured && <span className="absolute right-5 top-5 rounded-full bg-warning px-3 py-1 text-[10px] font-extrabold uppercase tracking-wider text-[#111]">Frota profissional</span>}<span className={`grid size-12 place-items-center rounded-xl [&_svg]:size-6 ${featured ? "bg-white/10 text-warning" : "bg-primary/8 text-primary"}`}>{icon}</span><h2 className={`mt-6 font-heading text-2xl font-extrabold ${featured ? "text-white" : "text-foreground"}`}>{name}</h2><p className={`mt-2 text-sm font-light ${featured ? "text-white/65" : "text-muted-foreground"}`}>{description}</p><div className="mt-8"><strong className="font-heading text-4xl font-extrabold tracking-[-.04em] md:text-5xl">{price}</strong><span className={`ml-2 text-xs font-semibold ${featured ? "text-white/60" : "text-muted-foreground"}`}>{suffix}</span></div><p className={`mt-3 text-sm font-bold ${featured ? "text-warning" : "text-primary"}`}>{limit} · validade vitalícia</p><div className={`my-7 h-px ${featured ? "bg-white/12" : "bg-primary/10"}`}/><ul className="space-y-3">{items.map((item)=><li key={item} className={`flex gap-2.5 text-sm ${featured ? "text-white/75" : "text-foreground/75"}`}><Check className={`mt-0.5 size-4 shrink-0 ${featured ? "text-warning" : "text-primary"}`}/>{item}</li>)}</ul><Button asChild size="lg" className={`mt-8 w-full ${featured ? "bg-warning text-[#111] hover:bg-[#ffd62a]" : ""}`}><Link href="/devenir-partenaire">Escolher {name} <ArrowRight className="size-4"/></Link></Button><p className={`mt-4 flex items-center justify-center gap-1.5 text-[11px] ${featured ? "text-white/50" : "text-muted-foreground"}`}><ShieldCheck className="size-3.5"/>Publicação sujeita a validação</p></article>;
}
